version: '3.1'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
        - postgresqldb
    ports:
        - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/openaiDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2019
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  postgresqldb:
    image: 'postgres'
    container_name: postgresqldb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2019